### ISSUE TITLE
Create Page "Trainingsplan"

### ISSUE THREAD

**Issue by oliverhees** [AliaksandraNovikava/capstone-alex#20]
## Value Proposition

As a user I want to be able to click through my training plan to do my exercises

## Description
![screenshot-excalidraw com-2023 07 20-10_22_41](https://github.com/AliaksandraNovikava/capstone-alex/assets/38748506/abb71adf-0d9d-4026-9173-93721f25fddd)

## Acceptance Criteria
- [ ] The username and the days that have passed since joining should be displayed.
- [ ] The headline "Your training plan" should be displayed
- [ ] A button "back" should be displayed
- [ ] A button "continue" should be displayed
- [ ] after clicking on the button "next" the next exercise is displayed
- [ ] after clicking on the button "back" the previous exercise is displayed

## Tasks

- [ ] create a featured branch
- [ ] create a page called "trainings plan"
- [ ] create a component to render exercises (from Dummydata in Globalstate)
- [ ] create a component for button "weiter"
- [ ] create a component for button "zurück"
